// Cloudflare Worker Radio Proxy - Generated by MagicBox Generator
const STATIONS = {
  "radio_1": "http://kythuatphatthanhtruyenhinh.vov.gov.vn:8001/;", // NTV Ninh Bình Radio
  "radio_2": "http://14.162.146.90:8000/HANOI90", // FM Hanoi 90 MHz
  "radio_3": "http://media.kythuatvov.vn:7059/;", // VOV Mekong FM
  "radio_4": "https://stream.zeno.fm/jxniabwipmhtv", // 99.8 Radio
  "radio_5": "http://14.224.130.186:8000/binhdinh", // Bình Định FM 97
  "radio_6": "http://222.252.21.96:8000/HANOI96", // FM Hanoi 96 MHz
  "radio_7": "https://ha-noi-community-radio.radiocult.fm/stream", // Há Nội Community Radio
  "radio_8": "https://stream.zeno.fm/yvzaxu2qe7duv", // Little Saigon Radio
  "radio_9": "https://stream.zeno.fm/xsct365wra0uv", // Phat thanh LSTV
  "radio_10": "https://qurantranslations.net/sound/English/AbdulBaset_AbdulSamad/002.mp3", // Quran in Vietnamese
  "radio_11": "https://stream.zeno.fm/5cyfrgpebkhvv", // Saigoner
  "radio_12": "https://stream.zeno.fm/u4fzlxveibcuv", // Sakar murli - Bkwsu VN Radio
  "radio_13": "http://carol.epichosts.co.uk:8270/live.mp3", // Scientific Sound Asia Radio
  "radio_14": "https://c13.radioboss.fm:8127/autodj", // Vietnamese National People
  "radio_15": "https://stream.zeno.fm/g91qxch7gv8uv", // Vietnam War Rock
  "radio_16": "https://stream.zeno.fm/pmagmhzfy38uv", // Zeno FM - Mien Tay
  "radio_17": "https://stream.zeno.fm/4q7y9hvkp2zuv", // Zeno FM - M Radio Việt Nam
  "radio_18": "https://stream.zeno.fm/38paz80m268uv", // Zeno FM - nhac remix
  "radio_19": "https://stream.zeno.fm/kdvw4dznx38uv", // Zeno FM - Nhac Tre
  "radio_20": "https://stream.zeno.fm/vgsusc7kw38uv", // Zeno FM - Nhac Vang
  "radio_21": "https://stream.zeno.fm/tk8atfbgtg8uv", // Zeno FM - Nhung ban Acoustic Cover
  "radio_22": "https://stream.zeno.fm/ojnttdbhgr7tv", // Zeno FM - VOZ FM
};
