// Cloudflare Worker Radio Proxy - Generated by MagicBox Generator
const STATIONS = {
  "radio_1": "https://str.vov.gov.vn/vovlive/vov1vov5Vietnamese.sdp_aac/playlist.m3u8", // VOV 1
  "radio_2": "https://strm.voh.com.vn/radio/channel5/playlist.m3u8", // VOH FM 87.7 Nhịp sống 77
  "radio_3": "https://stream.langsontv.vn/live/285c78da0c246524c90917842f8de03bd21/playlist.m3u8", // Lstv Lạng Sơn Radio
  "radio_4": "https://play.vovgiaothong.vn/live/gthn/playlist.m3u8", // VOV Giao thông Hà Nội
  "radio_5": "http://kythuatphatthanhtruyenhinh.vov.gov.vn:8001/;", // NTV Ninh Bình Radio
  "radio_6": "https://live.canthotv.vn/live/radio/playlist.m3u8", // Thtpct Thơ City Radio
  "radio_7": "https://streaming.tuyenquangtv.vn/channel/tuyenquang_radio/playlist.m3u8", // TTV Tuyên Quang Radio
  "radio_8": "http://14.162.146.90:8000/HANOI90", // FM Hanoi 90 MHz
  "radio_9": "https://live.baoquangninh.vn/qtvlive/qnr1.m3u8", // QNR1 Quảng Ninh Radio
  "radio_10": "https://cdn.sonlatv.vn/live/285bfb76d0d7a3c4615b853fe7a698e150c/playlist.m3u8", // STV Sơn La Radio
  "radio_11": "https://64d0d74b76158.streamlock.net/THDTR/thdtradio/playlist.m3u8", // Thdt Đồng Tháp Radio
  "radio_12": "https://live.baoquangninh.vn/qtvlive/qnr2.m3u8", // QNR2 Quảng Ninh Radio
  "radio_13": "http://media.kythuatvov.vn:7059/;", // VOV Mekong FM
  "radio_14": "https://stream.zeno.fm/jxniabwipmhtv", // 99.8 Radio
  "radio_15": "http://14.224.130.186:8000/binhdinh", // Bình Định FM 97
  "radio_16": "https://vnno-ne-2-tf-multi-playlist-zmp3.zmdcdn.me/j20SDlO5EQk/zhls/playback-realtime/audio/59a2ee0ed24b3b15625a/audio.m3u8", // CHẠM Radio
  "radio_17": "http://222.252.21.96:8000/HANOI96", // FM Hanoi 96 MHz
  "radio_18": "https://ha-noi-community-radio.radiocult.fm/stream", // Há Nội Community Radio
  "radio_19": "https://cloudstreamhntv.tek4tv.vn/live/smil:HN2.smil/playlist.m3u8", // Hanoi TV2
  "radio_20": "https://stream.zeno.fm/yvzaxu2qe7duv", // Little Saigon Radio
  "radio_21": "https://stream.zeno.fm/xsct365wra0uv", // Phat thanh LSTV
  "radio_22": "https://qurantranslations.net/sound/English/AbdulBaset_AbdulSamad/002.mp3", // Quran in Vietnamese
  "radio_23": "https://stream.zeno.fm/5cyfrgpebkhvv", // Saigoner
  "radio_24": "https://stream.zeno.fm/u4fzlxveibcuv", // Sakar murli - Bkwsu VN Radio
  "radio_25": "http://carol.epichosts.co.uk:8270/live.mp3", // Scientific Sound Asia Radio
  "radio_26": "https://c13.radioboss.fm:8127/autodj", // Vietnamese National People
  "radio_27": "https://stream.zeno.fm/g91qxch7gv8uv", // Vietnam War Rock
  "radio_28": "https://strm.voh.com.vn/radio/channel2/playlist.m3u8", // VOH AM 610 Nông thôn
  "radio_29": "https://strm.voh.com.vn/radio/channel1/playlist.m3u8", // VOH FM 95.6 Đêm thành phố
  "radio_30": "https://strm.voh.com.vn/radio/channel3/playlist.m3u8", // VOH FM 99.9 Không giới hạn
  "radio_31": "https://str.vov.gov.vn/vovlive/vov2.sdp_aac/playlist.m3u8", // VOV 6
  "radio_32": "https://stream.zeno.fm/pmagmhzfy38uv", // Zeno FM - Mien Tay
  "radio_33": "https://stream.zeno.fm/4q7y9hvkp2zuv", // Zeno FM - M Radio Việt Nam
  "radio_34": "https://stream.zeno.fm/38paz80m268uv", // Zeno FM - nhac remix
  "radio_35": "https://stream.zeno.fm/kdvw4dznx38uv", // Zeno FM - Nhac Tre
  "radio_36": "https://stream.zeno.fm/vgsusc7kw38uv", // Zeno FM - Nhac Vang
  "radio_37": "https://stream.zeno.fm/tk8atfbgtg8uv", // Zeno FM - Nhung ban Acoustic Cover
  "radio_38": "https://stream.zeno.fm/ojnttdbhgr7tv", // Zeno FM - VOZ FM
  "radio_39": "https://vnno-ne-3-tf-multi-playlist-zmp3.zmdcdn.me/BJ7DyJjfG_E/zhls/playback-realtime/audio/5bace800d4453d1b6454/audio.m3u8", // Zing Bolero
  "radio_40": "https://cdn.drt.vn/live/285a27750861b964c27af22091662a74f2f/playlist.m3u8", // Đài Phát thanh và Truyền hình Đắk Lắk
  "radio_41": "https://live.mediatech.vn/live/285bfb777e354ec43038aa68950adbac3a4/playlist.m3u8", // 
  "radio_42": "https://str.vov.gov.vn/vovlive/vovGTHCM.sdp_aac/playlist.m3u8", // 
};
